# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a22227902655b6f4fe4f70ce9031fa858d5ace1a1e04ced19a13deb8ca2f9dcb44e4ec29b0de5764ac9811ad0b27f6f2ce5708c67a13b2add9ee18de92320ce1

test:
  secret_key_base: 81a8dced933939a7821995df0d864f74b582d8c2ebfd3a322879288f12ac77e0329932e0d10c65257fcd90388b1b1606ab8c579bf7eace8865b3cf74e523b4b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
